import { renderToBuffer, Document, Page, Text, View } from '@react-pdf/renderer'
import { reportStyles as s } from '@/lib/pdf-report-styles'
import React from 'react'

// P2: the purchase-order PDF a vendor receives when a PO is sent. Same shared
// report styles as lib/inspection-pdf.tsx so both documents look like one system.
//
// This is the document the vendor works from, so everything on it is a SNAPSHOT
// of the PO at send time — no live lookups, no links back into the dashboard.

export type PoLine = {
  description?: string | null
  quantity?: number | string | null
  unit_cost?: number | string | null
  item?: { name?: string | null; sku?: string | null } | null
}

export type PoRecord = {
  po_number?: number | null
  status?: string | null
  expected_at?: string | null
  delivery_address?: string | null
  notes?: string | null
  created_at?: string | null
  vendor?: { company_name?: string | null; contact_name?: string | null; email?: string | null; payment_terms?: string | null } | null
  site?: { name?: string | null } | null
}

const money = (n: number) =>
  n.toLocaleString('en-SA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

export function poPdfDocument(po: PoRecord, lines: PoLine[], orgName: string) {
  const generatedAt = new Date().toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' })
  const total = lines.reduce((sum, l) => sum + Number(l.quantity ?? 0) * Number(l.unit_cost ?? 0), 0)

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.brand}>ServIQ-FM</Text>
            <Text style={s.brandSub}>Purchase Order</Text>
          </View>
          <View>
            <Text style={s.reportTitle}>PO #{po.po_number ?? '—'}</Text>
            <Text style={s.reportMeta}>{orgName} · {generatedAt}</Text>
          </View>
        </View>

        <View style={s.detailRow}><Text style={s.detailLabel}>Vendor</Text><Text style={s.detailValue}>{po.vendor?.company_name ?? '—'}{po.vendor?.contact_name ? ` (${po.vendor.contact_name})` : ''}</Text></View>
        <View style={s.detailRow}><Text style={s.detailLabel}>Payment Terms</Text><Text style={s.detailValue}>{po.vendor?.payment_terms ?? 'As agreed'}</Text></View>
        <View style={s.detailRow}><Text style={s.detailLabel}>Site</Text><Text style={s.detailValue}>{po.site?.name ?? '—'}</Text></View>
        <View style={s.detailRow}><Text style={s.detailLabel}>Deliver To</Text><Text style={s.detailValue}>{po.delivery_address ?? po.site?.name ?? '—'}</Text></View>
        <View style={s.detailRow}><Text style={s.detailLabel}>Expected By</Text><Text style={s.detailValue}>{po.expected_at ?? '—'}</Text></View>
        <View style={s.detailRow}><Text style={s.detailLabel}>Raised</Text><Text style={s.detailValue}>{po.created_at ? new Date(po.created_at).toLocaleDateString('en-GB') : '—'}</Text></View>

        <Text style={s.sectionTitle}>Order Lines</Text>
        <View style={s.table}>
          <View style={s.tableHeaderRow}>
            <View style={{ ...s.tableHeaderCell, width: '46%' }}><Text>Item</Text></View>
            <View style={{ ...s.tableHeaderCell, width: '14%' }}><Text>Qty</Text></View>
            <View style={{ ...s.tableHeaderCell, width: '20%' }}><Text>Unit (SAR)</Text></View>
            <View style={{ ...s.tableHeaderCell, width: '20%' }}><Text>Total (SAR)</Text></View>
          </View>
          {lines.length === 0 ? (
            <View style={s.tableRow}><View style={{ ...s.tableCell, width: '100%' }}><Text>No lines.</Text></View></View>
          ) : (
            lines.map((l, i) => (
              <View key={i} style={s.tableRow}>
                <View style={{ ...s.tableCell, width: '46%' }}>
                  <Text>{l.item?.name ?? l.description ?? '—'}{l.item?.sku ? ` (${l.item.sku})` : ''}</Text>
                </View>
                <View style={{ ...s.tableCell, width: '14%' }}><Text>{Number(l.quantity ?? 0)}</Text></View>
                <View style={{ ...s.tableCell, width: '20%' }}><Text>{money(Number(l.unit_cost ?? 0))}</Text></View>
                <View style={{ ...s.tableCell, width: '20%' }}>
                  <Text>{money(Number(l.quantity ?? 0) * Number(l.unit_cost ?? 0))}</Text>
                </View>
              </View>
            ))
          )}
          <View style={s.tableRow}>
            <View style={{ ...s.tableCell, width: '80%' }}><Text>Order total</Text></View>
            <View style={{ ...s.tableCell, width: '20%' }}><Text>{money(total)}</Text></View>
          </View>
        </View>

        {Boolean(po.notes) && (
          <>
            <Text style={s.sectionTitle}>Notes</Text>
            <Text style={s.paragraph}>{String(po.notes)}</Text>
          </>
        )}

        <View style={s.footer}>
          <Text style={s.footerText}>Generated by ServIQ-FM · {orgName} · {generatedAt}</Text>
        </View>
      </Page>
    </Document>
  )
}

/** Render the purchase order to a PDF buffer. */
export function poPdfBuffer(po: PoRecord, lines: PoLine[], orgName: string): Promise<Buffer> {
  return renderToBuffer(poPdfDocument(po, lines, orgName))
}
